package importer

/*
autogenerated JSON thanks to https://mholt.github.io/json-to-go/
 */
type Rulings struct {
	Date string `json:"date"`
	Text string `json:"text"`
}
type ForeignNames struct {
	Name         string `json:"name"`
	Text         string `json:"text"`
	Flavor       string `json:"flavor"`
	ImageURL     string `json:"imageUrl"`
	Language     string `json:"language"`
	Multiverseid int    `json:"multiverseid"`
}
type Legalities struct {
	Format   string `json:"format"`
	Legality string `json:"legality"`
}
type APIResponseForMultipleCards struct {
	Cards []Cards `json:"cards"`
}
type Cards struct {
	Name          string         `json:"name,omitempty"`
	ManaCost      string         `json:"manaCost,omitempty"`
	Cmc           float64        `json:"cmc,omitempty"`
	Colors        []string       `json:"colors,omitempty"`
	ColorIdentity []string       `json:"colorIdentity,omitempty"`
	Type          string         `json:"type,omitempty"`
	Supertypes    []string  	 `json:"supertypes,omitempty"`
	Types         []string       `json:"types,omitempty"`
	Subtypes      []string       `json:"subtypes,omitempty"`
	Rarity        string         `json:"rarity,omitempty"`
	Set           string         `json:"set,omitempty"`
	SetName       string         `json:"setName,omitempty"`
	Text          string         `json:"text,omitempty"`
	Flavor        string         `json:"flavor,omitempty"`
	Artist        string         `json:"artist,omitempty"`
	Number        string         `json:"number,omitempty"`
	Power         string         `json:"power,omitempty"`
	Toughness     string         `json:"toughness,omitempty"`
	Layout        string         `json:"layout,omitempty"`
	Multiverseid  int            `json:"multiverseid,omitempty"`
	ImageURL      string         `json:"imageUrl,omitempty"`
	Rulings       []Rulings  	 `json:"rulings,omitempty"`
	ForeignNames  []ForeignNames `json:"foreignNames,omitempty"`
	Printings     []string       `json:"printings,omitempty"`
	OriginalText  string         `json:"originalText,omitempty"`
	OriginalType  string         `json:"originalType,omitempty"`
	Legalities    []Legalities   `json:"legalities,omitempty"`
	ID            string         `json:"id,omitempty"`
	Quantity	  int 			 `json:"quantity"`
}
type APIResponseForOneCard struct {
	Card Card `json:"card"`
}
type Card struct {
	Name          string         `json:"name"`
	Cmc           float64        `json:"cmc"`
	Colors        []string `json:"colors"`
	ColorIdentity []string  `json:"colorIdentity"`
	Type          string         `json:"type"`
	Supertypes    []string  `json:"supertypes"`
	Types         []string       `json:"types"`
	Subtypes      []string  `json:"subtypes"`
	Rarity        string         `json:"rarity"`
	Set           string         `json:"set"`
	SetName       string         `json:"setName"`
	Text          string         `json:"text"`
	Flavor        string         `json:"flavor"`
	Artist        string         `json:"artist"`
	Number        string         `json:"number"`
	Layout        string         `json:"layout"`
	Multiverseid  int            `json:"multiverseid"`
	ImageURL      string         `json:"imageUrl"`
	Rulings       []Rulings  `json:"rulings"`
	ForeignNames  []ForeignNames `json:"foreignNames"`
	Printings     []string       `json:"printings"`
	OriginalText  string         `json:"originalText"`
	OriginalType  string         `json:"originalType"`
	Legalities    []Legalities   `json:"legalities"`
	ID            string         `json:"id"`
	Quantity	  int 			 `json:"quantity"`
}

//TODO: Will be the only response structs
type MTGDevAPIResponse struct {
	Cards []Cardss `json:"cards"`
}
type Rulingss struct {
	Date string `json:"date"`
	Text string `json:"text"`
}
type ForeignNamess struct {
	Name         string      `json:"name"`
	Text         string      `json:"text"`
	Flavor       string `json:"flavor"`
	ImageURL     string      `json:"imageUrl"`
	Language     string      `json:"language"`
	Multiverseid int         `json:"multiverseid"`
}
type Legalitiess struct {
	Format   string `json:"format"`
	Legality string `json:"legality"`
}
type Cardss struct {
	Name          string         `json:"name"`
	ManaCost      string         `json:"manaCost,omitempty"`
	Cmc           float64        `json:"cmc"`
	Colors        []string       `json:"colors"`
	ColorIdentity []string       `json:"colorIdentity"`
	Type          string         `json:"type"`
	Supertypes    []string  `json:"supertypes"`
	Types         []string       `json:"types"`
	Subtypes      []string  `json:"subtypes"`
	Rarity        string         `json:"rarity"`
	Set           string         `json:"set"`
	SetName       string         `json:"setName"`
	Text          string         `json:"text,omitempty"`
	Artist        string         `json:"artist"`
	Number        string         `json:"number"`
	Layout        string         `json:"layout"`
	Multiverseid  int            `json:"multiverseid,omitempty"`
	ImageURL      string         `json:"imageUrl,omitempty"`
	Rulings       []Rulingss      `json:"rulings"`
	ForeignNames  []ForeignNamess `json:"foreignNames"`
	Printings     []string       `json:"printings"`
	OriginalText  string         `json:"originalText,omitempty"`
	OriginalType  string         `json:"originalType,omitempty"`
	Legalities    []Legalitiess   `json:"legalities"`
	ID            string         `json:"id"`
	Flavor        string         `json:"flavor,omitempty"`
	Power         string         `json:"power,omitempty"`
	Toughness     string         `json:"toughness,omitempty"`
	Variations    []string       `json:"variations,omitempty"`
	Quantity	  int 			 `json:"quantity"`
}